name: time-stats-build

on:
  schedule:
    # Runs at 5:30am UTC
    - cron: '30 5 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          #GH_TOKEN: ${{ secrets.GH_TOKEN}}
          #USERNAME: guilyx
